server:
  port: 8040
spring:
  application:
    name: demo-zuul
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

management:
  security:
    enabled: false
zuul:
  routes:
    demo-consumer: /consumer/**
#忽略指定服务 多个服务 使用 ，分隔
#  ignored-services: demo-provider
#禁用过滤器方式  eg: xxxFilter.x.disable=true
#  PreRequestLogFilter.pre.disable: true
